version: '3.8'

services:
  # Chess bot - local mode
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    develop:
      watch:
        - path: ./backend
          target: /app
          action: sync
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - BOT_MODE=local
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    develop:
      watch:
        - path: ./frontend
          target: /app
          action: sync
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://backend:8000
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000 || exit 0"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s 