version: '3.8'

services:
  # Local self-play service with integrated viewer
  chess-bot:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes:
      - ./backend:/app:cached
    environment:
      - PYTHONUNBUFFERED=1
      - BOT_MODE=local
      - PYTHONPATH=/app
    ports:
      - "8000:8000"  # For web viewer
    command: python -m ai_chess_experiments.bot_runner --test

  # Online bot service
  chess-bot-online:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./backend:/app:cached
      - ./.env:/app/.env:ro
    environment:
      - PYTHONUNBUFFERED=1
      - BOT_MODE=online
    ports:
      - "8001:8000"  # For web viewer
    command: python -m ai_chess_experiments.bot_runner

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    command: npm start 